#%RAML 1.0 NamedExample

algorithm: QUVTL0NCQy9QS0NTNVBBRERJTkc=
encodedKey: itLubDhp2vliQiuin3PcrqPVsYIxsSeD
macSignature: N9Hkply0kMYN01TGE1P2BOrqY4RohQF2KkUJz53wewE=
parameters: BBB2TH/sAVq8WCpBc1wGa0Mo
